name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      -       - name: Build EXE (onedir)
        run: |
          pyinstaller --onedir --noconsole --name "EllaRenamer" --icon "icon.ico" renamer_gui.py

      - name: Zip artifact
        run: |
          powershell -Command "Compress-Archive -Path dist/EllaRenamer/* -DestinationPath EllaRenamer-Portable.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EllaRenamer-Portable
          path: EllaRenamer-Portable.zip

